#+TITLE:     Analytics Service Model
#+AUTHOR:    VLEAD
#+DATE:      2015-09-24 Thu
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: org-templates/level-0.org

* Introduction
  This documentation describes the requirements, design and
  implementation of analytics service.
  
  The purpose of the document is to show the analytics of all
  virtual-labs on vlab web page.

  *Note* : At the time of writing this document, vlab web page
  is [[http://www.vlabs.ac.in][www.vlabs.ac.in]]  

* Requirements
  1) Get the Total Number of Hits, Visits and Usage of all the
     virtual-labs.  If a User visits the lab page, then the server
     access log records all requests processed by the server.

     - HIT :: Each line in a log file of a particular lab is a single
              Hit.
	       
      The following example shows the sample log lines of =cse01= lab
      with 4 hits.
      #+BEGIN_EXAMPLE
      10.4.8.52 - - [08/Feb/2014:18:43:07 +0530] "GET /labs/cse01/index.php HTTP/1.1" 200 3241 "http://virtual-labs.ac.in/labs/cse01/" "Mozilla/5.0 (Linux; U; Android 4.1.2; en-in; Q500 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
      10.4.8.52 - - [08/Feb/2014:18:43:07 +0530] "GET /labs/cse01/css/default.css HTTP/1.1" 200 3338 "http://deploy.virtual-labs.ac.in/labs/cse01/index.php" "Mozilla/5.0 (Linux; U; Android 4.1.2; en-in; Q500 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
      10.4.8.52 - - [26/Jan/2014:05:26:22 +0530] "GET /labs/cse01/exp9/MinimumSpanningTree.swf HTTP/1.1" 304 - "http://web.iiit.ac.in/~sharada.mohanty/content/graph-visualisation-using-flash" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"
      10.4.8.52 - - [26/Jan/2014:05:32:48 +0530] "GET /labs/cse01/exp7/DFS_BFS.swf HTTP/1.1" 200 13567 "http://web.iiit.ac.in/~sharada.mohanty/content/graph-visualisation-using-flash" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"
      #+END_EXAMPLE
	       
     - Visit :: A Hit to a lab web page either html or php pages
                except js/css/images/pdf/doc files.

       The following example shows the sample log lines of =cse01= lab
                with 2 visits.
      #+BEGIN_EXAMPLE
      10.4.8.52 - - [08/Feb/2014:18:43:07 +0530] "GET /labs/cse01/index.php HTTP/1.1" 200 3241 "http://virtual-labs.ac.in/labs/cse01/" "Mozilla/5.0 (Linux; U; Android 4.1.2; en-in; Q500 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
      10.4.8.52 - - [08/Feb/2014:18:51:05 +0530] "GET /labs/cse01/exp1/UnarySystem.html HTTP/1.1" 200 642 "http://deploy.virtual-labs.ac.in/labs/cse01/exp1/index.php?section=Simulation" "Mozilla/5.0 (Linux; U; Android 4.1.2; en-in; Q500 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
      #+END_EXAMPLE

      *Note* : Observe =GET /labs/cse01/= column to know the visit
                count.

     - Usage :: 
       1) A Visit to the experiment of a lab and a Visit to the
          simulation of the same lab. Considering both visits
          are from same <ip-address>.
       2) If a user visits an experiment page and the
          simulation page with minimum of 'x' amount of time
          and maximum of 1 day, then it is counted as a usage.
       3) The Order in which the user visited the experiment
          page or simulation page is not considered.(Either the
          experiment page visited first or simulation page or
          vice versa).

	The following example shows the sample log lines of =cse01=
                lab with one Usage.
        #+BEGIN_EXAMPLE
	10.4.12.236 - - [09/Feb/2014:13:46:18 +0530] "GET /labs/cse01/exp2/index.php HTTP/1.1" 200 3591 "http://deploy.virtual-labs.ac.in/labs/cse01/index.php?section=List%20of%20experiments" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
	10.4.12.236 - - [09/Feb/2014:13:47:55 +0530] "GET /labs/cse01/exp2/index.php?section=Simulation HTTP/1.1" 200 3232 "http://deploy.virtual-labs.ac.in/labs/cse01/exp2/index.php?section=Theory" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
        #+END_EXAMPLE	
      

           *Note* : Hits, Visits and Usage is calculated from the logs of
           the labs which are hosted on IIIT-H Infrastrure and AWS. Labs on
	   IIIT-H are not at Level-5, hence these labs are running on
	   Individual containers.  The labs which are at level-5 are hosted
	   on AWS.

  2) Similarly, get the Total Number of Hits, Visits and Usage of each
     virtual-lab.
  3) Get the Number of Hits, visits and Usage from the respective
     institues for the labs which are hosted across the
     institutes(where ever the labs are hosted other than IIIT-H).
      
      *Note* : These numbers will be treated as 'constants' for total
      usage calculation

  4) The labs, which are deployed with only simulations, then a visit
     to the simulation is itself considered as usage.
  5) The labs, with-out simulations are not considered as usage. (Although
     hits and visits will be calculated)
  6) The number of users accessing a lab from the same <ip-address>
     (either from the same Institute or College), then the minimum
     number of the experiment page visits and simulation page visits
     is considered as usage.
  7) The log lines with HTTP response code 2** (success) will be
     considered for calculating the hits, visits and usage.  The log
     lines with HTTP response code 4** or 5** (error) will be
     ignored.

     The following example shows the sample log lines of =cse01= lab
     with response code =2**= (Observe 6th column from the following
     example). The logs with this response code should be considered
     for hits, visits and usage calculation.
     
     #+BEGIN_EXAMPLE
     10.4.8.52 - - [08/Feb/2014:18:43:07 +0530] "GET /labs/cse01/exp1/index.php HTTP/1.1" 200 3241 "http://virtual-labs.ac.in/labs/cse01/" "Mozilla/5.0 (Linux; U; Android 4.1.2; en-in; Q500 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
     10.4.8.52 - - [09/Feb/2014:13:46:18 +0530] "GET /labs/cse01/exp2/index.php HTTP/1.1" 200 3591 "http://deploy.virtual-labs.ac.in/labs/cse01/index.php?section=List%20of%20experiments" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
     #+END_EXAMPLE
      
     The following example shows the sample log lines of =cse01= lab
     with response codes =4**= and =5**= (Observe 6th column from the following
     example). The logs with this response codes should be ignored.

     #+BEGIN_EXAMPLE
     196.12.53.130 - - [04/Mar/2014:14:24:02 +0530] "GET /labs/cse01/index.php HTTP/1.1" 400 400 "-" "Mozilla/5.0 (Windows NT 6.1; rv:12.0) Gecko/20100101 Firefox/12.0"
     10.4.8.52 - - [24/Jun/2014:16:33:22 +0530] "GET /build/index.php HTTP/1.1" 404 250 "http://deploy.virtual-labs.ac.in/labs/cse01/index.php" "Mozilla/5.0 (Windows NT 6.1; rv:26.0) Gecko/20100101 Firefox/26.0"
     10.4.8.52 - - [24/Jun/2014:16:33:24 +0530] "GET /build/index.php HTTP/1.1" 502 500 "http://deploy.virtual-labs.ac.in/labs/cse01/index.php" "Mozilla/5.0 (Windows NT 6.1; rv:26.0) Gecko/20100101 Firefox/26.0"
     10.4.8.52 - - [24/Jun/2014:16:33:29 +0530] "GET /build/index.php HTTP/1.1" 503 414 "http://deploy.virtual-labs.ac.in/labs/cse01/index.php" "Mozilla/5.0 (Windows NT 6.1; rv:26.0) Gecko/20100101 Firefox/26.0"
     #+END_EXAMPLE
  8) The log lines with bots (Googlebot, bingbot, etc.) are not 
     considered for calculation of hits, visits and usage.

     The following example shows the sample log lines of =cse01= lab
     with Googlebot and bingbot. (Observe the last column from the following
     example). The logs with this bots to be ignored.

     #+BEGIN_EXAMPLE
     66.249.79.3 - - [02/Jan/2015:20:16:46 +0530] "GET /labs/cse01/exp8/index.php?section=Simulation HTTP/1.1" 200 3277 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
     10.4.8.52 - - [03/Jan/2015:17:55:42 +0530] "GET /labs/cse01/exp8/index.php?section=Simulation HTTP/1.1" 200 3277 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
     #+END_EXAMPLE
  9) The process to be defined on how to maintain analytics when:
     - A New lab gets Deployed/Hosted.
     - An Existing lab gets Deleted/Removed.
  10) The lab existing with multiple simulations per experiment, In such cases
      visit to any one simulation (among many) after visiting
      experiment will be considered as usage.

  11) The labs with tasks instead of simulations, then each visit
      to a task is counted as usage.
      
      The following example shows the sample log lines of =cse09= lab
      with simulation as tasks. (Observe the 5th column from the following
      example). 

      #+BEGIN_EXAMPLE
      10.4.12.236 - - [09/Feb/2014:16:49:17 +0530] "GET /labs/cse09/exp1/tasks.html HTTP/1.1" 200 429 "http://deploy.virtual-labs.ac.in/labs/cse09/exp1/interaction-frame.html" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"
      #+END_EXAMPLE

  12)  The vlabs landing page should display numbers for: Labs, Experiments, Visits, and Usage.

       *Note*: only "Visits" and "Usage" will be provided by analytics service model.

  13) Give a hyper link to the Usage. On click, it should open a web
      page with Analytics of all labs.  Mention on this page: "All
      data shown below is from January 20XX until today".

  14) Analytics of Top 5 labs among all labs should be display
      first. Rest of the labs analytics will be displayed according to
      the institutes.

  15) The web page that opens upon clicking Usage will have the following:

      a) Analytics of top 10 labs: 
         Labs-> Hits -> Visits -> Usage -> Average time spent

      b) Analytics of institutions 
         Institute -> Most popular lab -> Usage

      c) Analytics by months of the year
         Month -> Hits -> Visits -> Usage -> Average time spent

* COMMENT Display Analytics on Vlabs landing page     
#+BEGIN_SRC python :tangle all-total.txt
cse01 1234 2345 3450
cse02 2343 9979 8979
cse03 3123 3343 3432
#+END_SRC
#+BEGIN_SRC python :tangle total.txt
hits 1234 visits 5678 usage 2468
#+END_SRC

#+BEGIN_SRC python :tangle app.py
from flask import Flask, render_template, request, jsonify, make_response
from flask.ext.cache import Cache
import json

app = Flask(__name__)

app.config['CACHE_TYPE'] = 'simple'

app.cache = Cache(app)

@app.route('/analytics')
@app.cache.cached(timeout=360)
def total_hits():
    files_dir = "/home/madhavi/Documents/speed/"
    result_file = files_dir+"total.txt"
    with open(result_file, 'r') as f:
      lines = f.read()
      words = lines.split()
    d = {}
    d["hits"] = int (words[1])
    d["visits"]=int (words[3])
    d["usage"]=int (words[5])
    hits = jsonify(d)
    response = make_response(hits)
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Credentials'] = 'true'
    return response

@app.route('/analytics/labs')
@app.cache.cached(timeout=360)
def lab_wise_total():
    files_dir = "/home/madhavi/Documents/speed/"
    result_file = files_dir+"all-total.txt"
    rows = []
    d = {}
    with open(result_file, 'r') as f:
      lines = f.readlines()
      for line in lines:
         row = line.split()
         lab_id = row[0]
         d[lab_id]={}
         d[lab_id]["hits"]=int (row[1])
         d[lab_id]["visits"]=int (row[2])
         d[lab_id]["usage"]=int (row[3])
        
    response = make_response(jsonify(d))
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Credentials'] = 'true'
    return response


if __name__ == '__main__':
  app.run(port=5000, debug=True)

#+END_SRC
#+BEGIN_SRC 
<html>
  <head>
    <title>Analytics</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" language="javascript">
      window.onload = function() {
      $.getJSON('http://localhost:5000/analytics', function(data) {
      $("#hits").html(data["hits"]);
      $("#visits").html(data["visits"]);
      $("#usage").html(data["usage"]);
      });
      $.getJSON('http://localhost:5000/analytics/labs', function(data) {
      $("#cse01").html(data["cse01"]["hits"]);
      $("#cse02").html(data["cse02"]["hits"]);
      });
      };
      
    </script>
  </head>
  <body>
    <div id="hits" >
     Hit
    </div>
    <div id="visits">
      Visit
    </div>
    <div id="usage">
      Usage
    </div>
<div id="cse01-hits">
    </div>

<div id="cse02-hits">
      Computer Programming
    </div>

   </body>
</html>
#+END_SRC
