#+TITLE:     Building an application for the Analytics of Virtual Labs
#+AUTHOR:    VLEAD
#+DATE:      2015-09-24 Thu
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: org-templates/level-0.org

* Introduction
  This documentation describes the requirements, design and
  implementation of analytics service.
  
  The purpose of the document is to show the analytics of all
  virtual-labs on vlab web page.

  *Note* : At the time of writing this document, vlab web page
  is [[http://www.vlabs.ac.in][www.vlabs.ac.in]]  

* Requirements
** Requirement #1 
   Total Number of Hits, Visits and Usage of all labs.
   1) If a User visits the lab page, then the server access log
      records all requests processed by the server.
      - HIT :: Each line in a log file of a particular lab is a single
             Hit.
      - Visit :: A Hit to a lab web page either html or php pages except
               js/css/images/pdf/doc files.
      - Usage :: A Visit to the experiment of a lab and a Visit to the
               simulation of the same lab.Considering both visits are
               from same ip-address.
      *Note* : Hits, Visits and Usage is calculated from the logs of
      the labs which are hosted on IIIT-H Infrastrure and AWS. Labs on
      IIIT-H are not at Level-5, hence these labs are running on
      Individual containers.  The labs which are at level-5 are hosted
      on AWS.
   2) Get the Number of Hits, visits and Usage from the respective
      institues for the labs which are hosted across the
      institutes(where ever the labs are hosted other than IIIT-H).
